// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://noeilnfdhmhidtuuyxdb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vZWlsbmZkaG1oaWR0dXV5eGRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MzkyNDMsImV4cCI6MjA3MjMxNTI0M30.KrnvlOomka8wtKJdz-V-OL9BVqbKDX-jbmApjpbeEmo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});